apiVersion: apps/v1
kind: Deployment
metadata:
  name: visa-advisor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visa-advisor
  template:
    metadata:
      labels:
        app: visa-advisor
    spec:
      containers:
      - name: visa-advisor
        image: 985671710454.dkr.ecr.ap-south-1.amazonaws.com/visa-advisor:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"